# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-12-27T20:07:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import BaseModel, Field


class TaskOwner(Enum):
    """
    Task owner type
    """

    self = "self"
    external = "external"


class TaskStatus(Enum):
    """
    Task status enum
    """

    live = "live"
    paused = "paused"
    transmitting = "transmitting"
    stopped = "stopped"


class TaskType(Enum):
    """
    Task type enum
    """

    rx = "rx"
    tx = "tx"


class CreateRxTaskParams(BaseModel):
    """
    Parameters for creating an RX task
    """

    name: str = Field(..., title="Name")
    frequency: float = Field(..., title="Frequency")
    sample_rate: float = Field(..., alias="sampleRate", title="Samplerate")
    bandwidth: float = Field(..., title="Bandwidth")
    fft_size: int = Field(..., alias="fftSize", title="Fftsize")


class CreateTxTaskParams(BaseModel):
    """
    Parameters for creating a TX task
    """

    name: str = Field(..., title="Name")
    filename: str = Field(..., title="Filename")
    frequency: Optional[float] = Field(default=None, title="Frequency")
    loop: bool = Field(..., title="Loop")


class UpdateTaskParams(BaseModel):
    """
    Parameters for updating a task
    """

    name: Optional[str] = Field(default=None, title="Name")
    status: Optional[TaskStatus] = None
    frequency: Optional[float] = Field(default=None, title="Frequency")


class RecordingInfo(BaseModel):
    """
    Recording information
    """

    filename: str = Field(..., title="Filename")
    duration: float = Field(..., description="Recording duration in seconds", title="Duration")
    file_size: int = Field(
        ..., alias="fileSize", description="File size in bytes", title="Filesize"
    )
    is_recording: bool = Field(..., alias="isRecording", title="Isrecording")


class PlaybackInfo(BaseModel):
    """
    TX playback information
    """

    filename: str = Field(..., title="Filename")
    progress: float = Field(
        ..., description="Playback progress 0-1", ge=0.0, le=1.0, title="Progress"
    )
    is_looping: bool = Field(..., alias="isLooping", title="Islooping")
    duration: float = Field(..., description="Total duration in seconds", title="Duration")


class VisualizationMode(Enum):
    """
    Visualization mode for task data
    """

    fft_only = "fft-only"
    fft_waterfall = "fft-waterfall"
    spectrogram = "spectrogram"


class Status(Enum):
    """
    Current source status
    """

    idle = "idle"
    active = "active"
    error = "error"


class DataSource(BaseModel):
    """
    Information about an available data source
    """

    id: str = Field(..., description="Unique source identifier", title="Id")
    name: str = Field(..., description="Human-readable source name", title="Name")
    type: str = Field(..., description="Source type (e.g., 'spectral')", title="Type")
    type_label: str = Field(
        ..., alias="typeLabel", description="Short label for UI", title="Typelabel"
    )
    center_frequency: float = Field(
        ..., alias="centerFrequency", description="Center frequency in Hz", title="Centerfrequency"
    )
    sample_rate: float = Field(
        ..., alias="sampleRate", description="Sample rate in Hz", title="Samplerate"
    )
    status: Status = Field(..., description="Current source status", title="Status")
    parent_task_id: Optional[str] = Field(
        default=None,
        alias="parentTaskId",
        description="Parent task ID if this is a task output",
        title="Parenttaskid",
    )
    subscriber_count: Optional[int] = Field(
        default=0,
        alias="subscriberCount",
        description="Number of active subscribers",
        title="Subscribercount",
    )


class BitMetrics(BaseModel):
    """
    Metrics for a BIT test result
    """

    expected: Optional[str] = Field(default=None, title="Expected")
    actual: Optional[str] = Field(default=None, title="Actual")
    threshold: Optional[str] = Field(default=None, title="Threshold")
    unit: Optional[str] = Field(default=None, title="Unit")


class BitStatus(Enum):
    """
    Built-In Test (BIT) status values
    """

    ok = "ok"
    warn = "warn"
    fail = "fail"
    unknown = "unknown"


class BitSummary(BaseModel):
    """
    Summary counts for BIT test results
    """

    total: int = Field(..., title="Total")
    ok: int = Field(..., title="Ok")
    warn: int = Field(..., title="Warn")
    fail: int = Field(..., title="Fail")


class BitTest(BaseModel):
    """
    Atomic BIT test definition with rollup mappings
    """

    id: str = Field(..., title="Id")
    name: str = Field(..., title="Name")
    status: BitStatus
    description: Optional[str] = Field(default=None, title="Description")
    last_run: Optional[int] = Field(
        default=None, alias="lastRun", description="Unix timestamp in ms", title="Lastrun"
    )
    duration_ms: Optional[int] = Field(
        default=None, alias="durationMs", description="Duration in milliseconds", title="Durationms"
    )
    metrics: Optional[BitMetrics] = None
    function_nodes: Optional[list[str]] = Field(
        default=None, alias="functionNodes", description="Function node IDs", title="Functionnodes"
    )
    hardware_nodes: Optional[list[str]] = Field(
        default=None, alias="hardwareNodes", description="Hardware node IDs", title="Hardwarenodes"
    )


class BitTreeNode(BaseModel):
    """
    Rollup node used by functional and hardware hierarchies
    """

    id: str = Field(..., title="Id")
    name: str = Field(..., title="Name")
    status: BitStatus
    description: Optional[str] = Field(default=None, title="Description")
    children: Optional[list[BitTreeNode]] = Field(default=None, title="Children")
    tests: Optional[list[str]] = Field(
        default=None, description="IDs of tests mapped to this node", title="Tests"
    )


class BitAlertSeverity(Enum):
    """
    Severity level of a BIT alert
    """

    failed = "failed"
    degraded = "degraded"
    recovered = "recovered"


class TestFailureCount(BaseModel):
    """
    Failure count for a specific test
    """

    test_id: str = Field(..., alias="testId", title="TestId")
    test_name: str = Field(..., alias="testName", title="TestName")
    fail_count: int = Field(..., alias="failCount", title="FailCount")


class BitTestHistoryPoint(BaseModel):
    """
    Single point in test history
    """

    timestamp: int = Field(..., description="Unix timestamp in ms", title="Timestamp")
    status: BitStatus
    duration_ms: Optional[int] = Field(default=None, alias="durationMs", title="DurationMs")


class BitTestHistory(BaseModel):
    """
    Status history for a specific test
    """

    test_id: str = Field(..., alias="testId", title="TestId")
    test_name: str = Field(..., alias="testName", title="TestName")
    points: list[BitTestHistoryPoint] = Field(..., title="Points")


class UpdateStatus(Enum):
    """
    System update status
    """

    idle = "idle"
    uploading = "uploading"
    validating = "validating"
    installing = "installing"
    complete = "complete"
    error = "error"


class LockAcquireResponse(BaseModel):
    """
    Lock acquire response
    """

    lock_id: str = Field(..., alias="lockId", title="Lockid")
    expires_at: int = Field(..., alias="expiresAt", title="Expiresat")


class LockStatusResponse(BaseModel):
    """
    Lock status response
    """

    is_locked: bool = Field(..., alias="isLocked", title="Islocked")
    locked_by: Optional[str] = Field(default=None, alias="lockedBy", title="Lockedby")
    locked_since: Optional[int] = Field(default=None, alias="lockedSince", title="Lockedsince")
    expires_at: Optional[int] = Field(default=None, alias="expiresAt", title="Expiresat")


class InstallStartRequest(BaseModel):
    """
    Request body for starting installation
    """

    upload_id: str = Field(..., title="Upload Id")


class InstallStartResponse(BaseModel):
    """
    Install start response
    """

    install_id: str = Field(..., alias="installId", title="Installid")


class InstallStatusResponse(BaseModel):
    """
    Install status response
    """

    install_id: str = Field(..., alias="installId", title="Installid")
    status: UpdateStatus
    percent_complete: int = Field(..., alias="percentComplete", title="Percentcomplete")
    time_remaining_seconds: Optional[int] = Field(
        default=None, alias="timeRemainingSeconds", title="Timeremainingseconds"
    )
    current_step: Optional[str] = Field(default=None, alias="currentStep", title="Currentstep")
    error: Optional[str] = Field(default=None, title="Error")


class UploadStatusResponse(BaseModel):
    """
    Upload status response
    """

    upload_id: str = Field(..., alias="uploadId", title="Uploadid")
    status: UpdateStatus
    bytes_received: int = Field(..., alias="bytesReceived", title="Bytesreceived")
    total_bytes: int = Field(..., alias="totalBytes", title="Totalbytes")
    percent_complete: int = Field(..., alias="percentComplete", title="Percentcomplete")
    validation_results: Optional[dict[str, Any]] = Field(
        default=None, alias="validationResults", title="Validationresults"
    )
    error: Optional[str] = Field(default=None, title="Error")


class BodyUploadPackageApiSystemUpdateUploadPost(BaseModel):
    file: bytes = Field(..., title="File")


class ValidationError(BaseModel):
    loc: list[Union[str, int]] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class Task(BaseModel):
    """
    SDR Task
    """

    id: str = Field(..., title="Id")
    name: str = Field(..., title="Name")
    type: TaskType
    frequency: float = Field(..., description="Center frequency in Hz", title="Frequency")
    sample_rate: float = Field(
        ..., alias="sampleRate", description="Sample rate in Hz", title="Samplerate"
    )
    bandwidth: Optional[float] = Field(
        default=None, description="Bandwidth in Hz", title="Bandwidth"
    )
    fft_size: Optional[int] = Field(
        default=None, alias="fftSize", description="FFT size (bins)", title="Fftsize"
    )
    owner: TaskOwner
    owner_name: str = Field(
        ..., alias="ownerName", description="Owner display name", title="Ownername"
    )
    status: TaskStatus
    uptime: float = Field(..., description="Uptime in seconds", title="Uptime")
    recording: Optional[RecordingInfo] = None
    playback: Optional[PlaybackInfo] = None
    created_at: int = Field(
        ..., alias="createdAt", description="Unix timestamp in ms", title="Createdat"
    )
    fps: Optional[float] = Field(default=None, description="Current frame rate", title="Fps")
    visualization_mode: Optional[VisualizationMode] = Field(
        default=None, alias="visualizationMode", description="Visualization mode for task data"
    )


class BitResult(BaseModel):
    """
    BIT test suite result
    """

    timestamp: int = Field(..., description="Unix timestamp in ms", title="Timestamp")
    overall_status: BitStatus = Field(
        ...,
        alias="overallStatus",
        description="Overall system status derived from function tree rollup",
    )
    summary: BitSummary
    tests: list[BitTest] = Field(..., title="Tests")
    function_tree: BitTreeNode = Field(..., alias="functionTree")
    hardware_tree: BitTreeNode = Field(..., alias="hardwareTree")


class BitAlert(BaseModel):
    """
    Alert generated from BIT status transitions
    """

    id: int = Field(..., title="Id")
    timestamp: int = Field(..., description="Unix timestamp in ms", title="Timestamp")
    test_id: str = Field(..., alias="testId", title="TestId")
    test_name: str = Field(..., alias="testName", title="TestName")
    previous_status: Optional[BitStatus] = Field(default=None, alias="previousStatus")
    new_status: BitStatus = Field(..., alias="newStatus")
    severity: BitAlertSeverity
    message: str = Field(..., title="Message")


class BitAlertList(BaseModel):
    """
    List of BIT alerts with counts
    """

    alerts: list[BitAlert] = Field(..., title="Alerts")
    total_count: int = Field(..., alias="totalCount", title="TotalCount")


class BitHealthMetrics(BaseModel):
    """
    Health metrics over a time window
    """

    window_minutes: int = Field(..., alias="windowMinutes", title="WindowMinutes")
    snapshot_count: int = Field(..., alias="snapshotCount", title="SnapshotCount")
    operational_percent: float = Field(..., alias="operationalPercent", title="OperationalPercent")
    degraded_minutes: float = Field(..., alias="degradedMinutes", title="DegradedMinutes")
    non_op_minutes: float = Field(..., alias="nonOpMinutes", title="NonOpMinutes")
    failure_count: int = Field(..., alias="failureCount", title="FailureCount")
    top_failing_tests: list[TestFailureCount] = Field(
        ..., alias="topFailingTests", title="TopFailingTests"
    )


class HTTPValidationError(BaseModel):
    detail: Optional[list[ValidationError]] = Field(default=None, title="Detail")


BitTreeNode.update_forward_refs()
