# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spectral_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "spectral_data.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13spectral_data.proto\x12\x0bsdr_cockpit"g\n\x08\x46\x46TFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x13\n\x0b\x63\x65nter_freq\x18\x02 \x01(\x01\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x01\x12\x0c\n\x04\x62ins\x18\x04 \x01(\x0c\x12\x10\n\x08is_delta\x18\x05 \x01(\x08"\xbc\x01\n\rFFTFrameBatch\x12%\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x15.sdr_cockpit.FFTFrame\x12\x1c\n\x0f\x62\x61tch_timestamp\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12\x18\n\x0b\x63\x65nter_freq\x18\x03 \x01(\x01H\x01\x88\x01\x01\x12\x18\n\x0bsample_rate\x18\x04 \x01(\x01H\x02\x88\x01\x01\x42\x12\n\x10_batch_timestampB\x0e\n\x0c_center_freqB\x0e\n\x0c_sample_rate"\x8d\x02\n\x0fSpectralMessage\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.sdr_cockpit.SpectralMessage.MessageType\x12-\n\x0csingle_frame\x18\x02 \x01(\x0b\x32\x15.sdr_cockpit.FFTFrameH\x00\x12+\n\x05\x62\x61tch\x18\x03 \x01(\x0b\x32\x1a.sdr_cockpit.FFTFrameBatchH\x00\x12\x19\n\x0f\x63ompressed_data\x18\x04 \x01(\x0cH\x00"@\n\x0bMessageType\x12\x10\n\x0cSINGLE_FRAME\x10\x00\x12\t\n\x05\x42\x41TCH\x10\x01\x12\x14\n\x10\x43OMPRESSED_BATCH\x10\x02\x42\t\n\x07payloadb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "spectral_data_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FFTFRAME"]._serialized_start = 36
    _globals["_FFTFRAME"]._serialized_end = 139
    _globals["_FFTFRAMEBATCH"]._serialized_start = 142
    _globals["_FFTFRAMEBATCH"]._serialized_end = 330
    _globals["_SPECTRALMESSAGE"]._serialized_start = 333
    _globals["_SPECTRALMESSAGE"]._serialized_end = 602
    _globals["_SPECTRALMESSAGE_MESSAGETYPE"]._serialized_start = 527
    _globals["_SPECTRALMESSAGE_MESSAGETYPE"]._serialized_end = 591
# @@protoc_insertion_point(module_scope)
